(function(){ mollify.ui.texts.add('en', {
pluginNotificatorAdminNavTitle : "Notifications",
pluginNotificatorAdminNameTitle: "Name",
pluginNotificationAdminAddNotificationTitle: "Add Notification",
pluginNotificationAdminEditNotificationTitle: "Edit Notification",
pluginNotificationAdminAddNotificationMessage: "Enter the name for the new notification:",
pluginNotificationAdminEditNotificationMessage: "Enter new name for the notification:",
pluginNotificatorNotificationMessageTitle: "Message",
pluginNotificatorNotificationEventsTitle: "Events that trigger notification",
pluginNotificatorNotificationUsersTitle: "Users who receive notification",
pluginNotificatorNotificationEditMessageDialogTitle: "Edit notification message",
pluginNotificatorNotificationEditMessageTitle: "Title",
pluginNotificatorNotificationEditMessageMsg: "Message",
pluginNotificatorNotificationAddEventTitle: "Add event",
pluginNotificatorNotificationAddEventMessage: "Select event(s) to be added as notification trigger:",
pluginNotificatorNotificationAddUserTitle: "Add receiver",
pluginNotificatorNotificationAddUserMessage: "Select user(s) to be added as notification receiver:",
pluginNotificatorNotificationEditMessageVariablesTitle: "Variables",
pluginNotificatorNotificationEditMessageVariablesTxt: "For list of variables, see https://code.google.com/p/mollify/wiki/NotificatorPlugin",
pluginNotificatorNotificationEventUsersTitle: "Users that trigger the event",
pluginNotificatorNotificationAddEventUserTitle: "Add event users",
pluginNotificatorNotificationAddEventUserMessage: "Select user(s) to be added as notification trigger:",
pluginNotificatorNotificationNoEventUsersMsg: "Empty list will trigger the notification for any user"
})})();
