(function(){ mollify.texts.add('en', {
itemContextShareTitle: 'Share',
shareDialogTitle: 'Shares',
shareDialogNoShares: 'No shares',
shareDialogShareFileTitle: "Share file download",
shareDialogShareFolderTitle: 'Share folder upload',
shareDialogUnnamedShareTitle: 'Unnamed',
shareDialogItemLinkTitle: 'Show/hide link',
shareDialogItemInactiveLinkTitle: 'Inactive',
shareDialogShareLinkInstructions: 'Copy/paste the link below to access this share:',
shareDialogShareAddButton: 'Create new…',
shareDialogShareAddTitle: 'Create New Share',
shareDialogShareEditTitle: 'Edit Share',
shareDialogShareNameTitle: 'Name (optional):',
shareDialogShareLinkTitle: 'Link',
shareDialogShareActiveTitle: 'Active:',
shareDialogSave: 'Save',
shareDialogCancel: 'Cancel',
})})();