(function(){ mollify.texts.add('en', {
itemContextShareTitle: 'Share',
itemContextShareMenuTitle: 'Share…',
shareDialogTitle: 'Shares',
shareDialogNoShares: 'No shares',
shareDialogShareFileTitle: "Share file download",
shareDialogShareFolderTitle: 'Share folder upload',
shareDialogUnnamedShareTitle: 'Unnamed',
shareDialogItemLinkTitle: 'Show/hide link',
shareDialogItemInactiveLinkTitle: 'Inactive',
shareDialogShareLinkInstructions: 'Copy/paste the link below to access this share:',
shareDialogShareLinkCopyToClipboard: 'Copy to clipboard',
shareDialogShareAddButton: 'Create new…',
shareDialogShareAddTitle: 'Create New Share',
shareDialogShareEditTitle: 'Edit Share',
shareDialogShareGeneralTitle: 'General',
shareDialogShareNameTitle: 'Name (optional):',
shareDialogShareLinkTitle: 'Link',
shareDialogShareActiveTitle: 'Active:',
shareDialogShareValidityTitle: 'Validity',
shareDialogShareExpirationTitle: 'Expires at',
shareDialogSave: 'Save',
shareDialogCancel: 'Cancel',
})})();